name: Python Lint and Test

on:
  create:
    tags:
      - "*"

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: package
      run: |
        python -m build .
